"""
Generic Panel dashboard template.
"""

import panel as pn
import pandas as pd
import numpy as np
import plotly.express as px

from clean import load_salary_data, load_game_data, build_modeling_dataset
from model import run_logistic_regression, plot_decision_boundary

# -------------------------
# CONFIG
# -------------------------
CARD_WIDTH = 320


# -------------------------
# HELPER FUNCTIONS
# -------------------------
def load_data():
    salary = load_salary_data()
    games = load_game_data()
    return build_modeling_dataset(salary, games)


def get_position_pct_columns(df):
    """Return sortable list of position percentage columns for plotting."""
    excluded = {"W_PCT"}
    return sorted(
        [
            col
            for col in df.columns
            if col.endswith("_P") and col not in excluded and pd.api.types.is_numeric_dtype(df[col])
        ]
    )


def apply_filters(df, selected_team, year_range):
    """Apply shared dashboard filters to the modeling dataset."""
    filtered = df[(df["year"] >= year_range[0]) & (df["year"] <= year_range[1])]

    if selected_team != "All":
        filtered = filtered[filtered["team"] == selected_team]

    return filtered


def get_model_training_df(year_range):
    """Build a year-filtered dataframe for the logistic model functions in model.py."""
    df = load_data().copy()
    year_df = df[(df["year"] >= year_range[0]) & (df["year"] <= year_range[1])]

    required_cols = ["Offense_P", "Defense_P", "Playoffs", "team", "year"]
    if not set(required_cols).issubset(year_df.columns):
        return None, "Required model columns are missing in the dataset."

    model_df = year_df[required_cols].dropna().copy()
    if model_df.empty:
        return None, "No model rows available for the selected year range."

    if model_df["Playoffs"].nunique() < 2:
        return None, "Model needs both playoff and non-playoff examples in the selected range."

    return model_df, None


# -------------------------
# CALLBACK FUNCTIONS
# -------------------------
def get_table(selected_team, year_range, selected_metric):
    """
    Return a filtered table based on widget selections.
    """
    df = load_data().copy()

    df = apply_filters(df, selected_team, year_range)

    if df.empty:
        return pn.pane.Markdown("### No data available for the selected filters.")

    display_cols = [col for col in ["year", "team", selected_metric, "W", "W_PCT"] if col in df.columns]
    table_df = df[display_cols].sort_values(["year", "team"], ascending=[False, True])

    return pn.pane.DataFrame(table_df, sizing_mode="stretch_width", height=450)


def get_viz_scatter(selected_team, year_range, selected_metric, width, height):
    """Scatter plot adapted from viz.py (position spend vs win percentage)."""
    df = load_data().copy()
    df = apply_filters(df, selected_team, year_range)

    if df.empty:
        return pn.pane.Markdown("### No data available for the selected filters.")

    if selected_metric not in df.columns:
        return pn.pane.Markdown(f"### Metric '{selected_metric}' is not available.")

    chart_df = df[["team", "year", "W_PCT", selected_metric]].dropna()
    if chart_df.empty:
        return pn.pane.Markdown("### No plottable rows after removing missing values.")

    fig = px.scatter(
        chart_df,
        x=selected_metric,
        y="W_PCT",
        color="team",
        hover_data=["year"],
        title=f"NFL {selected_metric} vs. Win Percentage",
        labels={
            selected_metric: f"Percent of Cap Spent on {selected_metric}",
            "W_PCT": "Win Percentage",
            "team": "Team",
        },
        width=width,
        height=height,
    )

    fig.update_layout(legend_title_text="Team")
    return pn.pane.Plotly(fig, config={"displayModeBar": False})


def get_model_scatter(selected_team, year_range, width, height):
    """Decision-boundary image generated by model.py plotting function."""
    model_df, err = get_model_training_df(year_range)
    if err:
        return pn.pane.Markdown(f"### {err}")

    try:
        model, scaler, X, y = run_logistic_regression(model_df)
        out_path = Path(__file__).resolve().parent / "decision_boundary.png"
        plot_decision_boundary(
            model,
            scaler,
            X,
            y,
            ["Offense_P", "Defense_P"],
            show_plot=False,
            save_path=str(out_path),
        )
    except Exception as exc:
        return pn.pane.Markdown(f"### Could not generate model visualization: {exc}")

    note = "Model view uses Offense_P and Defense_P from model.py."
    if selected_team != "All":
        note += f" Team filter remains active for other tabs: **{selected_team}**."

    return pn.Column(
        pn.pane.Markdown(f"### Playoff Boundary from model.py\n{note}"),
        pn.pane.PNG(str(out_path), width=width, height=height),
    )


def get_logistic_metrics(selected_team, year_range):
    """Logistic metrics text generated by model.py + team prediction summary."""
    model_df, err = get_model_training_df(year_range)
    if err:
        return pn.pane.Markdown(f"### {err}")

    capture = io.StringIO()
    try:
        with redirect_stdout(capture):
            model, scaler, _, _ = run_logistic_regression(model_df)
    except Exception as exc:
        return pn.pane.Markdown(f"### Could not run model metrics: {exc}")

    metrics_text = capture.getvalue().strip()
    if not metrics_text:
        metrics_text = "No metrics were printed by model.py."

    year_df = load_data().copy()
    year_df = year_df[(year_df["year"] >= year_range[0]) & (year_df["year"] <= year_range[1])]

    if selected_team == "All":
        team_md = pn.pane.Markdown(
            "### Team Prediction\nChoose a team from the left controls for a team-level playoff prediction."
        )
    else:
        team_rows = year_df[year_df["team"] == selected_team].dropna(subset=["Offense_P", "Defense_P", "Playoffs"])
        if team_rows.empty:
            team_md = pn.pane.Markdown("### Team Prediction\nNo complete feature rows found for the selected team.")
        else:
            latest = team_rows.sort_values("year").iloc[-1]
            x_input = pd.DataFrame({"Offense_P": [latest["Offense_P"]], "Defense_P": [latest["Defense_P"]]})
            playoff_prob = model.predict_proba(scaler.transform(x_input))[0, 1]
            predicted = "Made Playoffs" if playoff_prob >= 0.5 else "No Playoffs"
            actual = "Made Playoffs" if int(latest["Playoffs"]) == 1 else "No Playoffs"
            team_md = pn.pane.Markdown(
                "\n".join(
                    [
                        "### Team Prediction",
                        f"- Team: **{selected_team}**",
                        f"- Season used: **{int(latest['year'])}**",
                        f"- Predicted playoff probability: **{playoff_prob:.2%}**",
                        f"- Predicted class: **{predicted}**",
                        f"- Actual class: **{actual}**",
                    ]
                )
            )

    return pn.Column(
        pn.pane.Markdown("### Logistic Metrics from model.py"),
        pn.pane.Markdown(f"```text\n{metrics_text}\n```"),
        team_md,
    )


def get_findings_text(selected_team, year_range, selected_metric):
    """High-level narrative summary for the dashboard overview."""
    df = load_data().copy()
    filtered = apply_filters(df, selected_team, year_range)

    if filtered.empty or selected_metric not in filtered.columns:
        return pn.pane.Markdown("### No findings available for current filters.")

    corr = filtered[[selected_metric, "W_PCT"]].dropna().corr().iloc[0, 1]
    direction = "positive" if corr > 0 else "negative"
    strength = "weak"
    if abs(corr) >= 0.6:
        strength = "strong"
    elif abs(corr) >= 0.3:
        strength = "moderate"

    scope = "all teams" if selected_team == "All" else selected_team
    return pn.pane.Markdown(
        "\n".join(
            [
                "### Project Story",
                "This dashboard explores how position-level salary allocation connects to team performance and playoff outcomes.",
                f"- Current scope: **{scope}**, seasons **{year_range[0]}-{year_range[1]}**",
                f"- Spend-vs-win signal for **{selected_metric}** is **{strength} {direction}** (correlation: **{corr:.3f}**)",
                "- Use the Model tabs to inspect the decision boundary and playoff classification performance.",
            ]
        )
    )


# -------------------------
# MAIN APP
# -------------------------
def main():
    pn.extension("tabulator")

    # -------------------------
    # LOAD DATA FOR WIDGET OPTIONS
    # -------------------------
    df = load_data()

    teams = ["All"] + sorted(df["team"].dropna().unique().tolist())
    metrics = get_position_pct_columns(df)
    if not metrics:
        metrics = [
            col
            for col in df.select_dtypes(include="number").columns
            if col not in {"year", "W", "W_PCT"}
        ]

    if not metrics:
        return pn.Column(
            pn.pane.Markdown("### No numeric spend metrics were found in the dataset.")
        )

    default_metric = "QB_P" if "QB_P" in metrics else metrics[0]
    min_year = int(df["year"].min())
    max_year = int(df["year"].max())

    # -------------------------
    # WIDGET DECLARATIONS
    # -------------------------
    team_select = pn.widgets.Select(
        name="Team",
        options=teams,
        value="All"
    )

    metric_select = pn.widgets.Select(
        name="Position Spend Metric",
        options=metrics,
        value=default_metric,
    )

    year_range_slider = pn.widgets.RangeSlider(
        name="Year Range",
        start=min_year,
        end=max_year,
        value=(min_year, max_year),
        step=1
    )

    width_slider = pn.widgets.IntSlider(
        name="Plot Width",
        start=600,
        end=1600,
        step=100,
        value=900
    )

    height_slider = pn.widgets.IntSlider(
        name="Plot Height",
        start=400,
        end=1200,
        step=100,
        value=600
    )

    # -------------------------
    # CALLBACK BINDINGS
    # -------------------------
    overview_text = pn.bind(
        get_findings_text,
        selected_team=team_select,
        year_range=year_range_slider,
        selected_metric=metric_select,
    )

    table = pn.bind(
        get_table,
        selected_team=team_select,
        year_range=year_range_slider,
        selected_metric=metric_select,
    )

    viz_scatter = pn.bind(
        get_viz_scatter,
        selected_team=team_select,
        year_range=year_range_slider,
        selected_metric=metric_select,
        width=width_slider,
        height=height_slider
    )

    model_scatter = pn.bind(
        get_model_scatter,
        selected_team=team_select,
        year_range=year_range_slider,
        width=width_slider,
        height=height_slider,
    )

    model_metrics = pn.bind(
        get_logistic_metrics,
        selected_team=team_select,
        year_range=year_range_slider,
    )

    # -------------------------
    # SIDEBAR CARDS
    # -------------------------
    filter_card = pn.Card(
        pn.Column(
            team_select,
            metric_select,
            year_range_slider,
        ),
        title="Filters",
        width=CARD_WIDTH,
        collapsed=False
    )

    plot_card = pn.Card(
        pn.Column(
            width_slider,
            height_slider
        ),
        title="Plot Settings",
        width=CARD_WIDTH,
        collapsed=True
    )

    # -------------------------
    # LAYOUT
    # -------------------------
    layout = pn.template.FastListTemplate(
        title="NFL Salary Performance Dashboard",
        sidebar=[
            filter_card,
            plot_card
        ],
        theme_toggle=False,
        main=[
            pn.Tabs(
                ("Overview", overview_text),
                ("Table", table),
                ("Salary vs Wins", viz_scatter),
                ("Playoff Boundary", model_scatter),
                ("Logistic Metrics", model_metrics),
                active=1
            )
        ]
    )

    layout.servable()
    return layout


if __name__ == "__main__":
    app = main()
    app.show()